Email template tables with photo [11.06.2024] [0.1.0]
araucaria-project/halina pull request #6
Opened 2024-06-11 11:39 UTC by CHMALU

- dodanie templatki do tworzenia maili z tabelą tekstem i zdjęciem

2024-06-11 12:10 UTC, ernestworkspace commented on src/halina/test.py
ten plik nie powinien być na gicie, a jeśli to powinien być unit test w katalogu z testami. W tej chwili używasz go tylko do sprawdzenia czy ci kod działa ale jak już będzie działał to totalnie jest on zbędny i dla innych użytkowników też nie jest on interesujący.

2024-06-11 12:10 UTC, ernestworkspace commented on src/halina/email_rapport/zdjecie.png
Trzeba uważać jak jest z prawami do wykorzystania tego zdjęcia. Podpowiedź: Tu potrzebujemy tylko do testu więc to może być cokolwiek z painta nawet.

2024-06-11 12:10 UTC, ernestworkspace commented on src/halina/email_rapport/email_builder.py
> -    async def build(self) -> str:
ta metoda powinna zostać albo jej ekwiwalent. Można zmienić tylko typ zwracany przez nią. PS: '-> str' za definicją funkcji wskazuje typ który ona zwraca w tym przypadku string

2024-06-11 12:10 UTC, ernestworkspace commented on src/halina/email_rapport/email_builder.py
Koncepcja tej klasy jest taka że jakaś metoda przeważająca dane wypełni tą klasę danymi poprzez "setery" a na końcu robie 'build' i dostaję 'coś' co przekazuje do mail sendera.

2024-06-11 12:18 UTC, CHMALU commented on src/halina/email_rapport/zdjecie.png
A to jakieś losowe zdjęcie z mojego komputera wziąłem. To jest akurat jakaś tapeta co gpt mi wczoraj wygenerował

2024-06-11 12:19 UTC, CHMALU commented on src/halina/test.py
a to przez przypadek go wrzuciłem właśnie w planie miałem żeby go nie dodawać. To go można wywalić

2024-06-11 13:04 UTC, ernestworkspace commented on src/halina/test.py
to usuń i zrób commita usuwającego

2024-06-11 13:08 UTC, ernestworkspace commented on src/halina/email_rapport/zdjecie.png
tak właśnie myślałem, mała szansa że ktoś będzie się o to przyczepiał ale dla spokoju jeśli chat gpt nie ma napisane w licencji że każde zdjęcie które wypluje jest opensorce to lepiej bym podmienił na coś innego. Możesz ten obrazek wstawić: 
https://github.com/araucaria-project/araucaria_webapp/blob/master/fw_web/static/araucaria_logo.png

2024-06-11 13:25 UTC, CHMALU commented on src/halina/test.py
zrobione

2024-06-11 13:26 UTC, CHMALU commented on src/halina/email_rapport/zdjecie.png
a to dopiero teraz zobazcyłem a wcześniej puściłem jakiegoś commita z napisaem test w paint haha

2024-06-26 11:02 UTC, ernestworkspace requested changes

2024-06-26 11:02 UTC, ernestworkspace commented on src/halina/email_rapport/resources/zdjecie.png
Usuń już to zdjęcie testowe z projektu, a miejsce w kodzie gdzie jest wstawiane zakomentuj. Jak będziemy mieli prawdziwe zdjęcie to się odkomętuje

2024-06-26 11:02 UTC, ernestworkspace commented on src/halina/email_rapport/telescope_data_collector.py
> +        self.objects: Dict[str, 0] = {}  # used dict instead list is faster
Czemu zmieniłeś typowanie?

2024-06-26 11:02 UTC, ernestworkspace commented on src/halina/email_rapport_service.py
> +    class SendEmailException(Exception):
To nie powinno być w klasie EmailRapportService tylko poza nią

2024-06-26 11:02 UTC, ernestworkspace commented on src/halina/main.py
> +    if platform.system() != 'Windows':
OK dla linuxsa ale co się stanie jak na windowsie uruchamiasz, nie ma żadnego sygnału przechwyconego

2024-06-26 11:04 UTC, ernestworkspace reviewed
.

2024-06-26 11:12 UTC, ernestworkspace approved these changes

2024-06-26 11:14 UTC, CHMALU commented on src/halina/email_rapport/telescope_data_collector.py
> +        self.objects: Dict[str, 0] = {}  # used dict instead list is faster
to jakiś misclick musiał być jak patrzyłem sobie co pobrać stamtąd

2024-06-26 11:18 UTC, ernestworkspace commented on src/halina/email_rapport_service.py
> +        email_builder = EmailBuilder()
nie o to chodzi w metodach buildera, w ten sposób używa się seterów linia po lini i za każdym razem odwołując się od nowa do email_builder. Te specyficzne metody wywołujesz tak:
email_builder.subject("subject").night(night).costam("costam")
można je zrobić w jednej linijce albo dla czytelności karzde ustawienie w osobnej ale bez wskazywania az każdym razem email_builder

2024-06-26 11:18 UTC, ernestworkspace commented on src/halina/email_rapport_service.py
> +    @staticmethod
to powinno być raczej prywatne jeśli używasz tylko lokalnie w tej klasie

2024-06-27 08:19 UTC, merged